# Relative path(s) to your source files
source: _sv

# Relative path where you want the documentation to be built
destination: styleguide

# The path that contains supporting assets for the documentation page
documentation_assets: ./_sv/node_modules/hologram-github-theme

# Category that will be used as the index.html (optional)
index: styleguide

# The global title that is displayed at the top of the pages
global_title: Styleguide

# The CSS files to be included in the styleguide
css_include:
  - '../_sv_custom.css'

ignore_paths:
  - "*stencil*"

# To output navigation for top level sections, set the value to
# 'section'. To output navigation for sub-sections, set the value to `all`
nav_level: section
